apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: final
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: paswrd
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: sql-data
  volumes:
    - name: sql-data
      persistentVolumeClaim:
        claimName: mysql-pvc
