apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: CLO835-role-binding
    namespace: final
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: CLO835
subjects:
  - kind: ServiceAccount
    name: clo835
    namespace: final