apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: final
  labels:
    name: webapp-deployment
spec:
  selector:
    matchLabels:
      name: simple-webapp-mysql
  replicas: 1
  template:
    metadata:
      namespace: final
      labels:
        app: ddogra1-app
        name: simple-webapp-mysql
    spec:
      serviceAccountName: clo835
      containers:
      - name: simple-webapp-mysql
        image: 951409759672.dkr.ecr.us-east-1.amazonaws.com/ddogra1-finalproject:WEBAPP_631f6f5445ecb83e6820944fd3fd2fabb9c1d636
        ports:
        - containerPort: 81
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 50m
        volumeMounts:
        - name: app-secret-volumes
          mountPath: "/opt/app-secret-volumes"
          readOnly: true
        envFrom:
          - secretRef:
              name: app-secret
          - configMapRef:
              name: app-s3-config
      volumes:
        - name: app-secret-volumes
          secret:
            secretName: app-secret