apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-mysql
  namespace: final
  labels:
    app: example-app
    name: simple-webapp-mysql
spec:
  serviceAccountName: clo835
  containers:
  - name: simple-webapp-mysql
    #image: kodekloud/simple-webapp-mysql:v10
    image: 951409759672.dkr.ecr.us-east-1.amazonaws.com/ddogra1-test:TEST_af60d754659db5c9227b8cf07017e8e0909cca3d
    ports:
    - containerPort: 81
    volumeMounts:
    - name: app-secret-volumes
      mountPath: "/opt/app-secret-volumes"
      readOnly: true
    envFrom:
      - secretRef:
          name: app-secret
      - configMapRef:
          name: app-s3-config
    env:
    - name: DB_Database
      value: mysql
  volumes:
    - name: app-secret-volumes
      secret:
        secretName: app-secret
